[build]
  command = "npm install"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/no-api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/no-api"
  status = 200
